### ISSUE TITLE
0.13.16 images missing on dockerhub

### ISSUE THREAD

**Issue by wlk** [lustefaniak/docker-sbt#3]
The 0.13.16 images are missing from dockerhub, see: https://hub.docker.com/r/lustefaniak/sbt/tags/

Errors during building: https://hub.docker.com/r/lustefaniak/sbt/builds/

**Comment by wlk** [comment]
this is the correct `curl` command: `curl -sL "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz"`

**Comment by wlk** [comment]
I would be happy to create PRs, but as part of PR on GitHub you cannot create new branches to the base repository

**Comment by lukasz-golebiewski** [comment]
This URL doesn't seem to work either

```
Step 9/11 : RUN curl -sL "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" | gunzip | tar -x -C /tmp/ && rm -r /usr/local && mv /tmp/sbt /usr/local && mkdir $HOME/.sbt && mv /usr/local/lib/local-preloaded $HOME/.sbt/preloaded
 ---> Running in 201f435cc17c
gunzip: invalid magic
tar: short read
```

**Comment by wlk** [comment]
@lukasz-golebiewski my bad,
The link I provided works only for 1.x branch

0.13.16 uses even different url format: https://cocl.us/sbt-0.13.16.tgz 

see: http://www.scala-sbt.org/download.html

**Comment by lukasz-golebiewski** [comment]
I think the error is that it's now a zip file, not a tgz

**Comment by lukasz-golebiewski** [comment]
Right, changed

**Comment by wlk** [comment]
@lukasz-golebiewski not sure what you mean, for 0.13.16 everything is ok other than the URL used to download the archive.

```bash
w@asus ~/Downloads $ file sbt-0.13.16.zip
sbt-0.13.16.zip: Zip archive data, at least v1.0 to extract
w@asus ~/Downloads $ file sbt-0.13.16.tgz
sbt-0.13.16.tgz: gzip compressed data, was "sbt.tar", from Unix, last modified: Wed Jul 26 23:15:31 2017, max compression
```

tbh, right now I really care only about 1.0 branch :)

**Comment by wlk** [comment]
my mistake here: https://github.com/lustefaniak/docker-sbt/issues/3#issuecomment-340569823 for this I actually was able to create a PR, but @lukasz-golebiewski created it first

**Comment by lukasz-golebiewski** [comment]
https://github.com/lustefaniak/docker-sbt/pull/5

**Comment by lukasz-golebiewski** [comment]
This looks like an issue in an upstream docker image:
https://hub.docker.com/r/1science/java/builds/

**Comment by lukasz-golebiewski** [comment]
I created a branch, feel free to submit a PR
https://github.com/lustefaniak/docker-sbt/tree/1.0.3_2.12.3
