### ISSUE TITLE
Sbt 1.0 support

### ISSUE THREAD

**Issue by wlk** [lustefaniak/docker-sbt#4]
Hi,
Do you have plans to add sbt 1.0 branch/support anytime soon?

**Comment by wlk** [comment]
This is the required change: https://github.com/wlk/docker-sbt/commit/e7e207f2905ac8922117e9605096eefe897bd6f4 sbt project moved the download location

**Comment by wlk** [comment]
For sbt 1.0 branch, I'm unable to create PRs - not possible to create new github branches as part of the PR - https://github.com/lustefaniak/docker-sbt/issues/3#issuecomment-340569823

**Comment by lukasz-golebiewski** [comment]
^ should no longer be a blocker

**Comment by lukasz-golebiewski** [comment]
Looks like there's an issue in an upstream docker image:
https://hub.docker.com/r/1science/java/builds/
I created a branch, feel free to submit a PR
https://github.com/lustefaniak/docker-sbt/tree/1.0.3_2.12.3

**Comment by wlk** [comment]
Thanks, I'll take a look soon
